# Generated by Django 4.2.7 on 2023-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperformance',
            name='fulfillment_rate',
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='average_response_time',
            field=models.DateTimeField(),
        ),
    ]
