# Generated by Django 4.2.7 on 2023-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_remove_historicalperformance_fulfillment_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperformance',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
